baseurl: ''
url: 'https://sofaschelseabogota.com'
name: Sofás Chelsea
title: Sofás Chelsea Bogotá - Muebles y comedores de calidad
celular: "3153433198"

permalink: :slug

markdown: kramdown

keep_files: [/img]

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []
